#!/bin/bash

module load python/2.7.2 
module load opencv/2.4.0

if [ $1 == "parallel" ] ; then
	mpiexec -n $2 python mpi_controller.py $3 $4 $5 $6 $7 $8
else
	python serial_controller.py $2 $3 $4 $5 $6
fi
